feat: improving the app by adding Logger for better monitoring, improving user data for cleaner deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,7 +21,7 @@ jobs:
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.AWS_REGION }}
 
-    # Login to ECR
+    # Login to ECR (-p exposes password in logs)
     - name: Login to ECR
       run: |
         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
@@ -51,7 +51,7 @@ jobs:
         echo "${{ secrets.EC2_KEY }}" > key.pem
         chmod 400 key.pem
 
-    # Deploy
+    # Deploy ("|| true": if it fails, ignore it. (Without it Pipeline fails and stops))
     - name: Deploy on EC2
       run: |
         ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
@@ -59,7 +59,7 @@ jobs:
         aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
         | docker login --username AWS --password-stdin \
         ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
-
+        
         docker stop devops-api || true
         docker rm devops-api || true
 
